on: push
jobs: 
  codecov-tests:
    name: Run Codecov test suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
      working-directory: ../
    - run: ls -la
    - run: npm install