on: push
jobs: 
  codecov-tests:
    name: Run Codecov test suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run coverage
    - run: npm test