name: Lint & Test Ubuntu
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install npm dependencies
      run: npm ci
    - name: Run linter
      run: npx eslint ./src
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install npm dependencies
      run: npm ci
    - name: Run test suite
      run: npm test
      env:
        SENDGRID_PASS: ${{ secrets.SENDGRID_PASS }}
        TWIT_ACCESS_TOKEN_SECRET: ${{ secrets.TWIT_ACCESS_TOKEN_SECRET }}
        TWIT_CONSUMER_SECRET: ${{ secrets.TWIT_CONSUMER_SECRET }}
        FOOTBALL_DATA_API_AUTH: ${{ secrets.FOOTBALL_DATA_API_AUTH }}
        SESSION_SECRET: "tekjskjdiqoexm"
    - name: Generate code coverage
      run: npm run coverage
    - name: Upload code coverage to codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true