on: push
jobs: 
  codecov-tests:
    name: Run Codecov test suite
    runs-on: ubuntu-latest
    steps:
    - name: Generate coverage report
      run: |
        npm install --global nyc codecov
        npm run coverage